"""Adiciona autor_filme ao modelo Filme

Revision ID: 1e6447fde175
Revises: da8c2e36e7d8
Create Date: 2024-10-27 16:10:25.263525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6447fde175'
down_revision = 'da8c2e36e7d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor_filme', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.drop_column('autor_filme')

    # ### end Alembic commands ###
