"""Criação das tabelas iniciais

Revision ID: da8c2e36e7d8
Revises: 
Create Date: 2024-10-27 15:39:56.925961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8c2e36e7d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessaofilme')
    with op.batch_alter_table('ingresso', schema=None) as batch_op:
        batch_op.alter_column('id_poltrona',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('qrcode',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_constraint('ingresso_id_usuario_fkey', type_='foreignkey')
        batch_op.drop_constraint('ingresso_id_sala_fkey', type_='foreignkey')
        batch_op.drop_constraint('ingresso_id_poltrona_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingresso', schema=None) as batch_op:
        batch_op.create_foreign_key('ingresso_id_poltrona_fkey', 'poltrona', ['id_poltrona'], ['id_poltrona'])
        batch_op.create_foreign_key('ingresso_id_sala_fkey', 'sala', ['id_sala'], ['id_sala'])
        batch_op.create_foreign_key('ingresso_id_usuario_fkey', 'usuario', ['id_usuario'], ['id_usuario'])
        batch_op.alter_column('qrcode',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('id_poltrona',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('sessaofilme',
    sa.Column('id_sessao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_filme', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_filme'], ['filme.id_filme'], name='sessaofilme_id_filme_fkey'),
    sa.ForeignKeyConstraint(['id_sessao'], ['sessao.id_sessao'], name='sessaofilme_id_sessao_fkey'),
    sa.PrimaryKeyConstraint('id_sessao', 'id_filme', name='sessaofilme_pkey')
    )
    # ### end Alembic commands ###
