"""Initial migration.

Revision ID: a9f9f33b24aa
Revises: 
Create Date: 2024-11-01 17:00:41.096742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f9f33b24aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salaingresso')
    op.drop_table('salasessao')
    op.drop_table('sessaofilme')
    with op.batch_alter_table('ingresso', schema=None) as batch_op:
        batch_op.alter_column('id_poltrona',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('ingresso_id_poltrona_fkey', type_='foreignkey')
        batch_op.drop_constraint('ingresso_id_sala_fkey', type_='foreignkey')

    with op.batch_alter_table('poltrona', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sala', ['id_sala'], ['id_sala'])

    with op.batch_alter_table('sala', schema=None) as batch_op:
        batch_op.alter_column('id_sessao',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'sessao', ['id_sessao'], ['id_sessao'])

    with op.batch_alter_table('sessao', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sala', ['id_sala'], ['id_sala'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sala', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_sessao',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('poltrona', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ingresso', schema=None) as batch_op:
        batch_op.create_foreign_key('ingresso_id_sala_fkey', 'sala', ['id_sala'], ['id_sala'])
        batch_op.create_foreign_key('ingresso_id_poltrona_fkey', 'poltrona', ['id_poltrona'], ['id_poltrona'])
        batch_op.alter_column('id_poltrona',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('sessaofilme',
    sa.Column('id_sessao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_filme', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_sessao', 'id_filme', name='sessaofilme_pkey')
    )
    op.create_table('salasessao',
    sa.Column('id_sala', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_sessao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_sala', 'id_sessao', name='salasessao_pkey')
    )
    op.create_table('salaingresso',
    sa.Column('id_sala', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_ingresso', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_sala', 'id_ingresso', name='salaingresso_pkey')
    )
    # ### end Alembic commands ###
